export const MARKET_SYMBOLS = [
  "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "ADAUSDT", "DOGEUSDT", "MATICUSDT",
  "DOTUSDT", "TRXUSDT", "LTCUSDT", "SHIBUSDT", "AVAXUSDT", "LINKUSDT", "ATOMUSDT", "UNIUSDT",
  "BCHUSDT", "XLMUSDT", "NEARUSDT", "FILUSDT", "ICPUSDT", "APTUSDT", "LDOUSDT", "HBARUSDT",
  "ETCUSDT", "KASUSDT", "ARBUSDT", "OPUSDT", "MKRUSDT", "AAVEUSDT", "RNDRUSDT", "INJUSDT",
  "STXUSDT", "SUIUSDT", "SEIUSDT", "TIAUSDT", "FETUSDT", "AGIXUSDT", "WLDUSDT", "ORDIUSDT", "PEPEUSDT"
] as const;

export type MarketSymbol = typeof MARKET_SYMBOLS[number];
